---
#################################
#################################
## Golangci-lint GitHub Actions #
#################################
#################################
name: Lint Code Base - Golang

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]
env:
  WORKING_DIR: ./app

###############
# Set the Job #
###############
jobs:
  lint:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ###########################
      # Install required golang #
      ###########################
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout code base
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      #############################
      # setup private repo access #
      #############################
      - name: Configure private repo access
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf http://github.com/
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base - Golangci
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{env.WORKING_DIR}}
          args: "--config .golangci.yml"